apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: banana-shop-login
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - banana.issessions.ca
      secretName: banana-shop-login-tls
  rules:
    - host: banana.issessions.ca
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: banana-shop-login
                port:
                  number: 5000
