apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: pwn-the-abtm
  labels:
    app: pwn-the-abtm
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pwn-the-abtm
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 0
