apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monkey-game3
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: suspicious.issessions.ca
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monkey-game3
                port:
                  number: 8000
