apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: big-biscuit
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - biscuit.issessions.ca
      secretName: big-biscuit-tls
  rules:
    - host: biscuit.issessions.ca
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: big-biscuit
                port:
                  number: 5000
