apiVersion: v1
kind: Service
metadata:
  name: monkey-no-see-monkey-no-do
  labels:
    app: monkey-no-see-monkey-no-do
spec:
  ports:
    - name: http-port
      port: 5000
  selector:
    app: monkey-no-see-monkey-no-do