apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: second-order
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - order.issessions.ca
      secretName: second-order-tls
  rules:
    - host: order.issessions.ca
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: second-order
                port:
                  number: 5000
