name: Move card
on: 
  pull_request:
    types: [opened]     
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "move_card"
  move_card:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v2
      # Runs a Python script
      - name: Moving card to TESTING
        run: python .github/workflows/cards.py --pull-request
        env:
          # Branch name
          BRANCH: ${{ github.head_ref }}
          # Github Access Token
          GITHUB_TOKEN: ${{ github.token }}
          # Repository owner & repository name
          REPO: ${{ github.repository }}

