apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hunt
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - hunt.issessions.ca
      secretName: hunt-tls
  rules:
    - host: hunt.issessions.ca
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hunt
                port:
                  number: 5000
