apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: account-creation
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - account.issessions.ca
      secretName: account-creation-tls
  rules:
    - host: account.issessions.ca
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: account-creation
                port:
                  number: 5000
