name: Build Challenge.yml
on: 
  pull_request:
    types: [opened, synchronize]     
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "move_card"
  build_challenge_yml:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v2
      # Runs a Python script
      - name: Build challenge.yml
        run: python .github/workflows/build.py -a
      # commit the challenge.yml file to repo
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          add: '--all'
          ref: ${{ github.event.pull_request.head.ref }}
